### PR TITLE
Moodycamel upgrade

### PR DESCRIPTION
**Pull request by stijnvanbeek**
- upgrade moodycamel concurrentqueue
- add moodycamel readerwriterqueue

### CODE REVIEW

**Comment by cklosters** [comment]
Hey, is there any way the upgrade of the third-party library can break existing functionality without the NAP PR being [merged](https://github.com/napframework/nap/pulls)? The thirdparty repo is not automatically tested (which it should be, looking into that). So a confirmation is important.

**Comment by stijnvanbeek** [comment]
All the old functionality is still available in the same place, so it shouldn't break anything.

**Comment by cklosters** [comment]
What I will do is merge it into our private repo, check if the builds pass and from there merge it into here. That way I can validate everything in the right order. Otherwise it's too dangerous.

**Comment by cklosters** [comment]
Hey, I [cherry picked ](https://github.com/napframework/thirdparty/commit/244fed7755d574ccd142f68458cd77efce2deea9)the required changes regarding `MoodyCamel`. I did this because otherwise the history of this repo would contain additional dependencies that were later reverted. This is cleaner. I already verified the changes and pushed to master. 

If this [PR ](https://github.com/napframework/nap/pull/7) now passes validation and all build checks I will start the review.

**Pull request closed without merging**
